### ISSUE TITLE
게임 커뮤니티

### ISSUE THREAD

**Issue by GeneralEffect** [dev-creffect/Planet-API#4]
예를 들어 크리펙트 게임 이미지를 클릭하면 

온라인 게임에서 방에 들어가듯이 게임 타임라인 페이지에 들어가져서 

그 게임에 관련된 글들을 모아 볼 수 있는것

(게시판?)

**Comment by Dr-robin** [comment]
#5 에서 각각 게임별 그룹들을 만들어지게 하죠
